rendezvous_server = 'remote-assistant.sfait.fr:21116'
nat_type = 1
serial = 0

[options]
local-ip-addr = '192.168.1.130'
key = 'CIib1hejuz7TSWXa19yUBcCiTfYqaY14aw5r3BXA89w='
relay-server = 'remote-assistant.sfait.fr'
custom-rendezvous-server = 'remote-assistant.sfait.fr'
api-server = 'https://remote-assistant.sfait.fr'
